--
-- PostgreSQL database dump
--

\restrict eDoVfq9LG712OqhuYxwgxWe2uzd7dha06aQoQhtDgCRbUk4ypUgjJJQTmcehoHy

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    address text,
    created_at timestamp(6) without time zone,
    email character varying(150),
    full_name character varying(200) NOT NULL,
    phone character varying(20)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expiry_tracking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expiry_tracking (
    id bigint NOT NULL,
    batch_number character varying(100),
    created_at timestamp(6) without time zone,
    expiry_date date NOT NULL,
    quantity integer NOT NULL,
    status character varying(30) NOT NULL,
    medicine_id bigint NOT NULL
);


ALTER TABLE public.expiry_tracking OWNER TO postgres;

--
-- Name: expiry_tracking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.expiry_tracking ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expiry_tracking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory (
    id bigint NOT NULL,
    last_updated timestamp(6) without time zone,
    location character varying(200),
    maximum_stock integer NOT NULL,
    minimum_stock integer NOT NULL,
    quantity integer NOT NULL,
    medicine_id bigint NOT NULL
);


ALTER TABLE public.inventory OWNER TO postgres;

--
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medicines; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medicines (
    id bigint NOT NULL,
    brand character varying(200) NOT NULL,
    category character varying(100),
    description text,
    name character varying(200) NOT NULL,
    price numeric(38,2),
    stock_quantity integer,
    batch_number character varying(100),
    created_at timestamp(6) without time zone,
    generic_name character varying(200),
    manufacturer character varying(200),
    medicine_code character varying(50),
    medicine_name character varying(200),
    selling_price numeric(12,2),
    unit_price numeric(12,2),
    supplier_id bigint
);


ALTER TABLE public.medicines OWNER TO postgres;

--
-- Name: medicines_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medicines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medicines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean,
    subject character varying(200),
    purchase_order_id bigint,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message text NOT NULL,
    notification_type character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    read_at timestamp(6) without time zone,
    related_medicine_id bigint,
    severity character varying(20),
    CONSTRAINT notifications_severity_check CHECK (((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prescriptions (
    id bigint NOT NULL,
    admin_notes text,
    created_at timestamp(6) without time zone,
    image_path character varying(500) NOT NULL,
    reviewed_at timestamp(6) without time zone,
    status character varying(20) NOT NULL,
    customer_id bigint NOT NULL,
    reviewed_by bigint,
    CONSTRAINT prescriptions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.prescriptions OWNER TO postgres;

--
-- Name: prescriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prescriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_order_items (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    medicine_id bigint NOT NULL,
    purchase_order_id bigint NOT NULL
);


ALTER TABLE public.purchase_order_items OWNER TO postgres;

--
-- Name: purchase_order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expected_delivery date,
    order_date date NOT NULL,
    order_number character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    supplier_id bigint NOT NULL
);


ALTER TABLE public.purchase_orders OWNER TO postgres;

--
-- Name: purchase_orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id integer NOT NULL,
    role_name character varying(50) NOT NULL,
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    description character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sale_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sale_items (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    subtotal numeric(12,2) NOT NULL,
    unit_price numeric(12,2) NOT NULL,
    medicine_id bigint NOT NULL,
    sale_id bigint NOT NULL
);


ALTER TABLE public.sale_items OWNER TO postgres;

--
-- Name: sale_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sale_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sale_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.sales (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    notes text,
    sale_number character varying(50) NOT NULL,
    sale_type character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    customer_id bigint NOT NULL,
    prescription_id bigint,
    sold_by bigint NOT NULL,
    CONSTRAINT sales_sale_type_check CHECK (((sale_type)::text = ANY ((ARRAY['WALK_IN'::character varying, 'PRESCRIPTION'::character varying])::text[])))
);


ALTER TABLE public.sales OWNER TO postgres;

--
-- Name: sales_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.sales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stock_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stock_logs (
    id bigint NOT NULL,
    action_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone,
    performed_by character varying(150),
    quantity integer NOT NULL,
    remarks text,
    medicine_id bigint NOT NULL,
    new_quantity integer,
    previous_quantity integer,
    CONSTRAINT stock_logs_action_type_check CHECK (((action_type)::text = ANY ((ARRAY['IN'::character varying, 'OUT'::character varying, 'ADJUSTMENT'::character varying])::text[])))
);


ALTER TABLE public.stock_logs OWNER TO postgres;

--
-- Name: stock_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stock_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stock_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: suppliers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.suppliers (
    id bigint NOT NULL,
    address character varying(500),
    city character varying(100),
    contact_person character varying(150),
    country character varying(100),
    created_at timestamp(6) without time zone,
    email character varying(150),
    phone character varying(20),
    state character varying(100),
    status character varying(20) NOT NULL,
    supplier_name character varying(200) NOT NULL,
    name character varying(200)
);


ALTER TABLE public.suppliers OWNER TO postgres;

--
-- Name: suppliers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.suppliers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.suppliers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id integer NOT NULL,
    email character varying(150) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone character varying(20),
    role_id bigint,
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    supplier_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, address, created_at, email, full_name, phone) FROM stdin;
1	Guntur\nGuntur	2026-08-10 21:18:48.261683	vishnurider7093@gmail.com	Vishnu vardhan	07093642508
2	hyd	2026-08-11 20:00:25.239407	raju@gmail.com	raju	9949773210
3	State Highway 21	2026-09-03 08:35:47.571468	23jr1a1289@gmail.com	charan	07093642508
\.


--
-- Data for Name: expiry_tracking; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expiry_tracking (id, batch_number, created_at, expiry_date, quantity, status, medicine_id) FROM stdin;
1	BATCH-2025-001	\N	2026-12-31	500	SAFE	1
2	BATCH-2025-002	\N	2026-06-30	200	SAFE	2
3	BATCH-2025-003	\N	2025-09-30	350	EXPIRING_SOON	3
4	BATCH-2025-004	\N	2027-03-31	120	SAFE	4
5	BATCH-2025-005	\N	2025-08-15	80	EXPIRING_SOON	5
6	BATCH-2025-006	\N	2024-12-31	30	EXPIRED	6
\.


--
-- Data for Name: inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory (id, last_updated, location, maximum_stock, minimum_stock, quantity, medicine_id) FROM stdin;
1	2026-08-04 15:19:01.312623	Shelf A1	1000	50	500	1
2	2026-08-04 15:19:01.312623	Shelf B1	500	30	200	2
4	2026-08-04 15:19:01.312623	Shelf D1	300	20	120	4
5	2026-08-04 15:19:01.312623	Shelf E1	200	25	80	5
6	2026-08-04 15:19:01.312623	Shelf F1	900	60	450	6
7	2026-08-04 15:19:01.312623	Shelf G1	600	40	300	7
8	2026-08-04 15:19:01.312623	Shelf H1	400	30	150	8
10	2026-08-04 15:19:01.312623	Shelf J1	250	25	90	10
11	2026-08-10 21:09:53.853377	Shelf A-15	500	10	50	14
3	2026-08-11 13:58:09.202083	Shelf C1	800	40	349	3
12	2026-09-03 08:34:11.033908	Main Pharmacy	500	10	0	15
\.


--
-- Data for Name: medicines; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medicines (id, brand, category, description, name, price, stock_quantity, batch_number, created_at, generic_name, manufacturer, medicine_code, medicine_name, selling_price, unit_price, supplier_id) FROM stdin;
1	Cipla Ltd	Analgesic	Pain reliever and fever reducer	Paracetamol 500mg	\N	\N	BATCH-2025-001	\N	Acetaminophen	Cipla Ltd	MED001	Paracetamol 500mg	5.00	2.50	\N
2	Sun Pharma	Antibiotic	Broad-spectrum antibiotic	Amoxicillin 250mg	\N	\N	BATCH-2025-002	\N	Amoxicillin	Sun Pharma	MED002	Amoxicillin 250mg	15.00	8.00	\N
3	Dr Reddys	Antidiabetic	Oral diabetes medicine for type 2 diabetes	Metformin 500mg	\N	\N	BATCH-2025-003	\N	Metformin HCl	Dr Reddys	MED003	Metformin 500mg	6.50	3.00	\N
4	Ranbaxy	Cardiovascular	Used to lower cholesterol and triglycerides	Atorvastatin 10mg	\N	\N	BATCH-2025-004	\N	Atorvastatin Calcium	Ranbaxy	MED004	Atorvastatin 10mg	12.00	5.00	\N
5	Cipla Ltd	Gastrointestinal	Proton pump inhibitor for acid reflux	Omeprazole 20mg	\N	\N	BATCH-2025-005	\N	Omeprazole	Cipla Ltd	MED005	Omeprazole 20mg	9.00	4.00	\N
6	Sun Pharma	Antihistamine	Antihistamine for allergic reactions	Cetirizine 10mg	\N	\N	BATCH-2025-006	\N	Cetirizine HCl	Sun Pharma	MED006	Cetirizine 10mg	4.00	1.50	\N
7	Bayer	Cardiovascular	Blood thinner and pain reliever	Aspirin 75mg	\N	\N	BATCH-2025-007	\N	Acetylsalicylic Acid	Bayer	MED007	Aspirin 75mg	5.50	2.00	\N
8	Cipla Ltd	Analgesic	Nonsteroidal anti-inflammatory drug	Ibuprofen 400mg	\N	\N	BATCH-2025-008	\N	Ibuprofen	Cipla Ltd	MED008	Ibuprofen 400mg	7.00	3.50	\N
10	Dr Reddys	Cardiovascular	Used to treat high blood pressure	Losartan 50mg	\N	\N	BATCH-2025-010	\N	Losartan Potassium	Dr Reddys	MED010	Losartan 50mg	14.00	6.00	\N
14	AstraZeneca	Gastrointestinal	Proton pump inhibitor capsule	Omeprazole 3130 mg	\N	\N	AZ-2026-3130	2026-08-10 21:09:53.786775	Omeprazole	AstraZeneca	MED-3130	Omeprazole 3130 mg	18.00	8.50	9
15	charan	Antibiotics		cinopthilin	\N	\N	BATCH-52899	2026-09-03 08:34:10.985207	ayurvedic	charan	MED-12345	cinopthilin	890.00	670.00	3
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, content, created_at, is_read, subject, purchase_order_id, receiver_id, sender_id) FROM stdin;
1	Hi Admin, Amoxicillin stock is running low. Should we issue a new Purchase Order?	2026-08-10 21:28:24.622177	f	Stock Reorder Request	\N	1	7
2	Approved! I have created PO-2026-041 with Cipla Distributors.	2026-08-10 21:28:24.644251	f	Re: Stock Reorder Request	\N	7	1
3	Hello Admin, shipment for PO-2026-041 has been dispatched via BlueDart logistics.	2026-08-10 21:28:24.646386	f	Shipment Dispatched	\N	1	10
5	Hello Pharmacist, checking in on the stock count for Paracetamol.	2026-08-10 21:29:14.701974	f	Direct Admin Message	\N	2	1
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, message, notification_type, status, title, read_at, related_medicine_id, severity) FROM stdin;
2	\N	Diclofenac 50mg stock is below minimum level. Current: 50, Minimum: 500	LOW_STOCK	UNREAD	Low Stock Alert: Diclofenac	\N	\N	\N
3	\N	Ranitidine 150mg stock is below minimum level. Current: 100, Minimum: 200	LOW_STOCK	UNREAD	Low Stock Alert: Ranitidine	\N	\N	\N
4	\N	Aspirin 75mg batch BATCH-2025-007 has expired on 2026-07-01	EXPIRY_ALERT	UNREAD	Expiry Alert: Aspirin	\N	\N	\N
5	\N	Pantoprazole 40mg batch BATCH-2025-011 has expired on 2026-06-01	EXPIRY_ALERT	READ	Expiry Alert: Pantoprazole	\N	\N	\N
6	\N	Diclofenac 50mg batch BATCH-2025-013 expired on 2026-05-20	EXPIRY_ALERT	READ	Expiry Alert: Diclofenac	\N	\N	\N
7	\N	Metformin 500mg batch BATCH-2025-003 expires on 2026-09-10	EXPIRY_ALERT	UNREAD	Expiring Soon: Metformin	\N	\N	\N
8	\N	Omeprazole 20mg batch BATCH-2025-005 expires on 2026-08-05	EXPIRY_ALERT	UNREAD	Expiring Soon: Omeprazole	\N	\N	\N
9	\N	Purchase Order PO-2025-001 from Cipla Distributors has been received	PURCHASE_ALERT	READ	Purchase Order Received	\N	\N	\N
10	\N	Purchase Order PO-2025-003 from Dr Reddys Wholesale has been approved	PURCHASE_ALERT	UNREAD	Purchase Order Approved	\N	\N	\N
14	2026-08-10 21:29:14.722291	Hello Pharmacist, checking in on the stock count f...	LOW_STOCK	UNREAD	New Message from Admin User	\N	\N	\N
15	2026-08-11 13:58:09.202083	Sale #SALE-A4D2353A created for customer Vishnu vardhan. Total: ₹6.5	LOW_STOCK	UNREAD	New Sale Processed	\N	\N	\N
1	\N	Pantoprazole 40mg stock is below minimum level. Current: 80, Minimum: 300	LOW_STOCK	READ	Low Stock Alert: Pantoprazole	2026-08-19 14:59:30.473561	\N	\N
22	2026-08-21 21:15:18.062648	Purchase order #PO-118016-FA22 created for supplier Cipla Distributors	PURCHASE_ALERT	UNREAD	New Purchase Order Created	\N	\N	INFO
23	2026-08-21 21:27:03.921161	Purchase order #PO-823916-E89B created for supplier Cipla Distributors	PURCHASE_ALERT	UNREAD	New Purchase Order Created	\N	\N	INFO
24	2026-08-21 21:47:24.732894	Purchase order #PO-44716-718C created for supplier Zydus Pharma	PURCHASE_ALERT	UNREAD	New Purchase Order Created	\N	\N	INFO
\.


--
-- Data for Name: prescriptions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prescriptions (id, admin_notes, created_at, image_path, reviewed_at, status, customer_id, reviewed_by) FROM stdin;
\.


--
-- Data for Name: purchase_order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_order_items (id, quantity, subtotal, unit_price, medicine_id, purchase_order_id) FROM stdin;
1	100	500.00	5.00	1	1
2	400	800.00	2.00	2	2
3	150	2250.00	15.00	3	3
4	25	200.00	8.00	2	4
5	25	200.00	8.00	2	5
6	50	400.00	8.00	2	6
\.


--
-- Data for Name: purchase_orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.purchase_orders (id, created_at, expected_delivery, order_date, order_number, status, total_amount, updated_at, supplier_id) FROM stdin;
1	2026-08-21 19:19:41.301025	2026-08-23	2026-08-16	PO-2026-001	RECEIVED	1200.00	2026-08-21 19:19:41.301025	1
2	2026-08-21 19:19:41.380479	2026-08-24	2026-08-19	PO-2026-002	SHIPPED	2400.00	2026-08-21 19:19:41.380479	2
3	2026-08-21 19:19:41.388959	2026-08-26	2026-08-20	PO-2026-003	APPROVED	4500.00	2026-08-21 19:19:41.388959	3
4	2026-08-21 21:15:18.025319	\N	2026-08-21	PO-118016-FA22	PENDING	200.00	2026-08-21 21:15:18.025319	1
5	2026-08-21 21:27:03.918014	\N	2026-08-21	PO-823916-E89B	PENDING	200.00	2026-08-21 21:27:03.918014	1
6	2026-08-21 21:47:24.716964	\N	2026-08-21	PO-44716-718C	APPROVED	400.00	2026-08-21 21:47:34.083169	6
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (role_id, role_name, id, created_at, description) FROM stdin;
1	ADMIN	1	\N	Full system access - manage users, medicines, suppliers, inventory, orders, reports
2	PHARMACIST	2	\N	Manage medicines, update inventory, create purchase orders, view reports
3	STORE_MANAGER	3	\N	Manage inventory, stock, view purchase orders, receive deliveries
4	VIEWER	4	\N	Read-only access - view dashboard, medicines, reports
5	SUPPLIER	5	2026-08-10 20:56:12.780621	Supplier Partner Role
6	STAFF	6	2026-08-11 13:55:15.52626	Staff Role - Limited Inventory Access
\.


--
-- Data for Name: sale_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sale_items (id, quantity, subtotal, unit_price, medicine_id, sale_id) FROM stdin;
2	1	6.50	6.50	3	2
\.


--
-- Data for Name: sales; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.sales (id, created_at, notes, sale_number, sale_type, status, total_amount, customer_id, prescription_id, sold_by) FROM stdin;
2	2026-08-11 13:58:09.169864		SALE-A4D2353A	WALK_IN	COMPLETED	6.50	1	\N	1
\.


--
-- Data for Name: stock_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stock_logs (id, action_type, created_at, performed_by, quantity, remarks, medicine_id, new_quantity, previous_quantity) FROM stdin;
1	IN	2026-08-10 21:09:53.8503	admin@medistock.com	50	Initial stock arrival shipment	14	50	0
3	OUT	2026-08-11 13:58:09.165842	admin@medistock.com	1	Dispensed via sale SALE-A4D2353A	3	349	350
\.


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.suppliers (id, address, city, contact_person, country, created_at, email, phone, state, status, supplier_name, name) FROM stdin;
1	123 Pharma Street	Mumbai	Rajesh Kumar	India	\N	rajesh@cipla.com	9800000001	Maharashtra	ACTIVE	Cipla Distributors	\N
2	456 Medical Ave	Ahmedabad	Priya Sharma	India	\N	priya@sunpharma.com	9800000002	Gujarat	ACTIVE	Sun Pharma Supply	\N
3	789 Health Road	Hyderabad	Vikram Singh	India	\N	vikram@drreddys.com	9800000003	Telangana	ACTIVE	Dr Reddys Wholesale	\N
4	321 Medicine Lane	Delhi	Sanjay Gupta	India	\N	sanjay@ranbaxy.com	9800000004	Delhi	ACTIVE	Ranbaxy Pharma	\N
5	654 Drug Street	Pune	Meena Patel	India	\N	meena@bayer.com	9800000005	Maharashtra	ACTIVE	Bayer Healthcare	\N
6	987 Pharma Park	Vadodara	Arjun Mehta	India	\N	arjun@zydus.com	9800000006	Gujarat	ACTIVE	Zydus Pharma	\N
7	100 Park Avenue	Cambridge	David Miller	USA	2026-08-10 21:07:26.648253	orders@astrazeneca-test.com	9988776655	MA	ACTIVE	AstraZeneca Pharmaceuticals	\N
9	100 Park Avenue	Cambridge	David Miller	USA	2026-08-10 21:09:53.725185	orders_3130@astrazeneca-test.com	9988773130	MA	ACTIVE	AstraZeneca Labs 3130	AstraZeneca Labs 3130
10	Guntur	Gutur	Vishnu vardhan	India	2026-08-11 20:08:16.761721	vishnurider7093@gmail.com	+917093642508	Andhra Pradesh	ACTIVE	raju	raju
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, email, full_name, password, phone, role_id, id, created_at, first_name, last_name, status, updated_at, supplier_id) FROM stdin;
12	vishnurider7093@gmail.com	Vishnu vardhan	$2a$10$ldAz4vrn00Li7QI/XnnXVedPAyPe7hwbtepTfT3McKhiDfqxyM58q	+917093642508	1	12	2026-08-21 19:35:04.453218	Vishnu	vardhan	ACTIVE	2026-08-21 19:35:04.453218	\N
2	john@medistock.com	John Pharmacist	$2a$10$ctVvN5cNBc3WWQpZSWAcqubOHEyPBBdm3lhMUsgenXdvBPzMJFvTi	9876543211	2	2	\N	John	Pharmacist	ACTIVE	\N	\N
3	jane@medistock.com	Jane Manager	$2a$10$ctVvN5cNBc3WWQpZSWAcqubOHEyPBBdm3lhMUsgenXdvBPzMJFvTi	9876543212	3	3	\N	Jane	Manager	ACTIVE	\N	\N
4	bob@medistock.com	Bob Viewer	$2a$10$ctVvN5cNBc3WWQpZSWAcqubOHEyPBBdm3lhMUsgenXdvBPzMJFvTi	9876543213	4	4	\N	Bob	Viewer	ACTIVE	\N	\N
5	alice@medistock.com	Alice Smith	$2a$10$ctVvN5cNBc3WWQpZSWAcqubOHEyPBBdm3lhMUsgenXdvBPzMJFvTi	9876543214	2	5	\N	Alice	Smith	ACTIVE	\N	\N
6	testuser@medistock.com	Test User	$2a$10$ctVvN5cNBc3WWQpZSWAcqubOHEyPBBdm3lhMUsgenXdvBPzMJFvTi	9998887770	1	6	2026-08-04 15:25:33.545764	Test	User	ACTIVE	2026-08-04 15:25:33.545764	\N
1	admin@medistock.com	Admin User	$2a$10$BXLeTEWYg3qRI77oVcFN8.HY..Eg.WxvRByuarhEQJGoFORjfSBVe	9876543210	1	1	\N	Admin	User	ACTIVE	2026-09-03 08:31:19.060614	\N
7	pharmacist@medistock.com	Pharmacist Staff	$2a$10$9uKI8GuTdRuCL2pFamxYMOu7WHFOsVuI14wbDqDTIYAmWqlykjhWO	9876543210	2	7	2026-08-10 20:56:12.97396	Pharmacist	Staff	ACTIVE	2026-09-03 08:31:19.222837	\N
8	store_manager@medistock.com	Store Manager	$2a$10$V2JuzWlKVCfW/8aLPPk2YuMd3HVWAL4f1Zv0mKTbSCFEaMQ2Ij7xS	9876543210	3	8	2026-08-10 20:56:13.108596	Store	Manager	ACTIVE	2026-09-03 08:31:19.348741	\N
9	viewer@medistock.com	Staff Viewer	$2a$10$KZNlgYNGvwIG9JTXTg/BhOwnwSlkqipSk9SkBh8aEy1BuKrDU6Onm	9876543210	4	9	2026-08-10 20:56:13.228754	Staff	Viewer	ACTIVE	2026-09-03 08:31:19.469729	\N
11	staff@medistock.com	Staff Member	$2a$10$Pjr4neOff3lI7Tq0s.By.OfDQHoXpGlKDJ65s9luUYT7ELV79w1f2	9876543210	6	11	2026-08-11 13:55:16.226024	Staff	Member	ACTIVE	2026-09-03 08:31:19.594596	\N
10	supplier@medistock.com	Supplier Partner	$2a$10$luTJo.tiqvfREAeSq5TAduqzh0ubxJSYNE.2BXpQ/uTbAKk8kr8S6	9876543210	5	10	2026-08-10 20:56:13.356651	Supplier	Partner	ACTIVE	2026-09-03 08:31:19.721722	\N
\.


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 3, true);


--
-- Name: expiry_tracking_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expiry_tracking_id_seq', 15, true);


--
-- Name: inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_id_seq', 12, true);


--
-- Name: medicines_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medicines_id_seq', 15, true);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 5, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 24, true);


--
-- Name: prescriptions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prescriptions_id_seq', 1, true);


--
-- Name: purchase_order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_order_items_id_seq', 6, true);


--
-- Name: purchase_orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.purchase_orders_id_seq', 6, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 6, true);


--
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 6, true);


--
-- Name: sale_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sale_items_id_seq', 3, true);


--
-- Name: sales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.sales_id_seq', 3, true);


--
-- Name: stock_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stock_logs_id_seq', 4, true);


--
-- Name: suppliers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.suppliers_id_seq', 10, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 12, true);


--
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 12, true);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: expiry_tracking expiry_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expiry_tracking
    ADD CONSTRAINT expiry_tracking_pkey PRIMARY KEY (id);


--
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- Name: medicines medicines_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicines
    ADD CONSTRAINT medicines_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: prescriptions prescriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT prescriptions_pkey PRIMARY KEY (id);


--
-- Name: purchase_order_items purchase_order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT purchase_order_items_pkey PRIMARY KEY (id);


--
-- Name: purchase_orders purchase_orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT purchase_orders_pkey PRIMARY KEY (id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: sale_items sale_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT sale_items_pkey PRIMARY KEY (id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (id);


--
-- Name: stock_logs stock_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_logs
    ADD CONSTRAINT stock_logs_pkey PRIMARY KEY (id);


--
-- Name: suppliers suppliers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT suppliers_pkey PRIMARY KEY (id);


--
-- Name: inventory uk1ifnxfibuor93cgurx4wri69h; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT uk1ifnxfibuor93cgurx4wri69h UNIQUE (medicine_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: roles uk716hgxp60ym1lifrdgp67xt5k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);


--
-- Name: medicines ukld4htm04xvhtv2rfn0motojql; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicines
    ADD CONSTRAINT ukld4htm04xvhtv2rfn0motojql UNIQUE (medicine_code);


--
-- Name: sales ukn0mb9m597xrmi5jbiogh74174; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT ukn0mb9m597xrmi5jbiogh74174 UNIQUE (sale_number);


--
-- Name: purchase_orders uknqsdqb8p2iobsmeaa2jxxw7k; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT uknqsdqb8p2iobsmeaa2jxxw7k UNIQUE (order_number);


--
-- Name: suppliers ukq5uvp89ra4ksaty5ghyaw4kjr; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.suppliers
    ADD CONSTRAINT ukq5uvp89ra4ksaty5ghyaw4kjr UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: medicines fk2e48d78mqo59nm84g3o4gflp8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medicines
    ADD CONSTRAINT fk2e48d78mqo59nm84g3o4gflp8 FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);


--
-- Name: messages fk4ui4nnwntodh6wjvck53dbk9m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk4ui4nnwntodh6wjvck53dbk9m FOREIGN KEY (sender_id) REFERENCES public.users(user_id);


--
-- Name: sale_items fk5n4yp9pqhplomtpumrrm8yudx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk5n4yp9pqhplomtpumrrm8yudx FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);


--
-- Name: sale_items fk7tcpbc5c5mpnm8fl2phl8ep7l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sale_items
    ADD CONSTRAINT fk7tcpbc5c5mpnm8fl2phl8ep7l FOREIGN KEY (sale_id) REFERENCES public.sales(id);


--
-- Name: purchase_order_items fkb8eixqn0uouxtyixl57mmuq3a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT fkb8eixqn0uouxtyixl57mmuq3a FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);


--
-- Name: sales fkd94vrikapjd2ews1k4lb71sfg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkd94vrikapjd2ews1k4lb71sfg FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: prescriptions fkfe1q7gg11wuuta4v50801dcby; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT fkfe1q7gg11wuuta4v50801dcby FOREIGN KEY (reviewed_by) REFERENCES public.users(user_id);


--
-- Name: stock_logs fkfsguggfchvubatv5xeao9qxo5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stock_logs
    ADD CONSTRAINT fkfsguggfchvubatv5xeao9qxo5 FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);


--
-- Name: users fkhptydrocfmpyv0pjmbmuc1yhx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkhptydrocfmpyv0pjmbmuc1yhx FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);


--
-- Name: messages fkk70tbrosd4efgjih7o5tnhooc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkk70tbrosd4efgjih7o5tnhooc FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id);


--
-- Name: sales fkmrp778xksm1veq75o6bpqtsxl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkmrp778xksm1veq75o6bpqtsxl FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id);


--
-- Name: inventory fkmv2v2jhyx6h3sw1l36hjqps2i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT fkmv2v2jhyx6h3sw1l36hjqps2i FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);


--
-- Name: prescriptions fkngc597c25d8ebdgnmrqjm79fd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT fkngc597c25d8ebdgnmrqjm79fd FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- Name: purchase_order_items fko3yj8ocbw2kav38548t22hgh8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_order_items
    ADD CONSTRAINT fko3yj8ocbw2kav38548t22hgh8 FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id);


--
-- Name: expiry_tracking fkp0qtb6gniu3shx7s86ou8lg82; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expiry_tracking
    ADD CONSTRAINT fkp0qtb6gniu3shx7s86ou8lg82 FOREIGN KEY (medicine_id) REFERENCES public.medicines(id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: purchase_orders fkrpdasmb8y8xs5tiy4369xpinq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_orders
    ADD CONSTRAINT fkrpdasmb8y8xs5tiy4369xpinq FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id);


--
-- Name: sales fkse28xurkqlj662q439tqumdlb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fkse28xurkqlj662q439tqumdlb FOREIGN KEY (sold_by) REFERENCES public.users(user_id);


--
-- Name: messages fkt05r0b6n0iis8u7dfna4xdh73; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkt05r0b6n0iis8u7dfna4xdh73 FOREIGN KEY (receiver_id) REFERENCES public.users(user_id);


--
-- PostgreSQL database dump complete
--

\unrestrict eDoVfq9LG712OqhuYxwgxWe2uzd7dha06aQoQhtDgCRbUk4ypUgjJJQTmcehoHy

